### ISSUE TITLE
Connection Refused Error

### ISSUE THREAD

**Issue by rahul606** [telefonicaid/fiware-figway#8]
Having error on connection with host http://130.206.80.40:5371/iot/devices

Traceback (most recent call last):
  File "RegisterDevice.py", line 82, in <module>
    r = requests.post(URL, data=PAYLOAD, headers=HEADERS)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))

**Comment by synergiator** [comment]
To comment with more details on this problem, we consider that the IDAS API instance is no more available.

We have the data from this tutorial:
http://fiwaretourguide.readthedocs.io/en/latest/connection-to-the-internet-of-things/how-to-read-measures-captured-from-iot-devices/

And same host is also referenced in the Instances section of the Catalogue:
http://catalogue.fiware.org/enablers/backend-device-management-idas/instances

Tracerout goes to:  fiwat-router.red.rediris.es

**Comment by GerfriedC** [comment]
OK any pointers to an updated tutorial?
ConnectionError: HTTPConnectionPool(host='cloud.lab.fi-ware.org', port=4730): Max retries exceeded with url: /v2.0/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028E8E158D08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
